config/routes.rb
Rails.application.routes.draw do
  root 'brands#index'
  devise_for :users
  resources :brands
  resources :phones
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  validates :country, presence: true

  has_many :phones
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  validates :brand, presence: true
  validates :year, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 2003 }
  validates :battery, presence: true

  belongs_to :brand
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      flash[:notice] = 'Successfully Added'
      redirect_to root_path
    else
      flash[:notice] = @brand.errors.full_messages.join('. ')
      render :new
    end
  end

  def index
    @brands = Brand.all
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :country)
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def new
    @phone = Phone.new
    @brands = Brand.all
  end

  def create
    @phone = Phone.new(phone_params)
    @brands = Brand.all
    if @phone.save
      flash[:notice] = 'Successfully Added'
      redirect_to phones_path
    else
      flash[:notice] = @phone.errors.full_messages.join('. ')
      render :new
    end
  end

  def index
    @phones = Phone.all
  end

  private

  def phone_params
    params.require(:phone).permit(:brand_id, :year, :battery, :description)
  end

end

app/views/brands/index.html.erb
<%= link_to 'Phones For Sale', phones_path %><br>
<%= link_to 'Add New Brand', new_brand_path %>

<table>
  <tr>
    <th>Brand</th>
  </tr>
  <% @brands.each do |brand| %>
    <tr>
      <td><%= brand.name %></td>
    </td>
  <% end %>
</table>

app/views/brands/new.html.erb
<div class="small-4">
  <%= form_for @brand do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :country %>
    <%= f.text_field :country %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cellphones</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Cellphones</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <div class="row">
    <div class="column">
      <%- flash.each do |key, value| -%>
        <div class="flash flash-<%= key %>">
          <%= value %>
        </div>
      <%- end -%>

      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/phones/index.html.erb
<%= link_to 'Brands List', root_path %><br>
<%= link_to 'Add New Phone', new_phone_path %>

<table>
  <tr>
    <th>Year</th>
    <th>Brand</th>
    <th>Battery</th>
    <th>Description</th>
  </tr>
  <% @phones.each do |phone| %>
    <tr>
      <td><%= phone.year %></td>
      <td><%= phone.brand.name %></td>
      <td><%= phone.battery %></td>
      <td><%= phone.description %></td>
    </tr>
  <% end %>
</table>

app/views/phones/new.html.erb
<div class="small-4">
  <% if !@brands.nil? %>
    <%= form_for @phone do |f| %>
      <%= f.label :brand %>
      <%= f.collection_select(:brand_id, @brands, :id, :name, include_blank: "Please select") %>
      <%= f.label :year %>
      <%= f.text_field :year %>
      <%= f.label :battery %>
      <%= f.text_field :battery %>
      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= f.submit 'Submit' %>
    <% end %>
  <% end %>
</div>